spring.application.name=zakat

spring.datasource.url=jdbc:mysql://localhost:3306/zakat?useSSL=false&allowPublicKeyRetrieval=false
spring.datasource.username=root
spring.datasource.password=Database2233

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

currencies_url = https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies.json
currency_url = https://latest.currency-api.pages.dev/v1/currencies/