name: Workflow

on:
    push:
      branches:
        - c#v3

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome to github actions workflow"

      - name: Checkout repository
        uses: actions/checkout@v7.0.0   

      - name: List repository files
        run: ls -la
